openapi: 3.0.3
info:
  title: ''
  version: 0.0.0
paths:
  /cardiouser/:
    get:
      operationId: cardiouser_list
      tags:
      - cardiouser
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
          description: ''
    post:
      operationId: cardiouser_create
      tags:
      - cardiouser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/User'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
  /cardiouser/{id}/:
    get:
      operationId: cardiouser_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - cardiouser
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
    put:
      operationId: cardiouser_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - cardiouser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/User'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
    patch:
      operationId: cardiouser_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - cardiouser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedUser'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedUser'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedUser'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
    delete:
      operationId: cardiouser_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - cardiouser
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /cardiouser/getdeseaserate/{id}/:
    get:
      operationId: cardiouser_getdeseaserate_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - cardiouser
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /getcardiodata/:
    get:
      operationId: getcardiodata_retrieve
      tags:
      - getcardiodata
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
components:
  schemas:
    PatchedUser:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 100
        age:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
        gender:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
        height:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
        weight:
          type: number
          format: double
        ap_hi:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
        ap_lo:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
        cholesterol:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
        gluc:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
        smoke:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
        alco:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
        active:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
        cardisrate:
          type: number
          format: double
    User:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 100
        age:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
        gender:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
        height:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
        weight:
          type: number
          format: double
        ap_hi:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
        ap_lo:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
        cholesterol:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
        gluc:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
        smoke:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
        alco:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
        active:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
        cardisrate:
          type: number
          format: double
      required:
      - active
      - age
      - alco
      - ap_hi
      - ap_lo
      - cardisrate
      - cholesterol
      - gender
      - gluc
      - height
      - id
      - name
      - smoke
      - weight
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
