# Generated by Django 5.0.3 on 2024-03-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(max_length=3)),
                ('gender', models.CharField(max_length=10)),
                ('height', models.IntegerField(max_length=3)),
                ('weight', models.FloatField(max_length=3)),
                ('ap_hi', models.IntegerField(max_length=3)),
                ('ap_lo', models.IntegerField(max_length=3)),
                ('cholesterol', models.IntegerField(max_length=1)),
                ('gluc', models.IntegerField(max_length=1)),
                ('smoke', models.IntegerField(max_length=1)),
                ('alco', models.IntegerField(max_length=1)),
                ('active', models.IntegerField(max_length=1)),
                ('cardisrate', models.FloatField(max_length=1)),
            ],
        ),
    ]
